sudo: false
language: java
jdk:
  - oraclejdk8

stages:
  - name: test
    if: not branch =~ ^release.*$
  - name: publish
    if: branch =~ ^release.*$

before_cache:
  # No sense in caching current build artifacts
  rm -rf $HOME/.m2/repository/org/postgresql

cache:
  directories:
    - '$HOME/.m2/repository'

matrix:
  include:
    - stage: publish
      script: .travis/deploy.sh

# Deploy snapshots to Maven Central
after_success:
  - "[[ $TRAVIS_BRANCH == 'master' ]] && mvn clean deploy --settings settings.xml"
